name: Native Image - Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  clean_release:
    name: 'Clean the native release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
 
      - name: Clean release and tag
        run: |
          gh release delete release-native --cleanup-tag -y || true
          echo "::notice title=release release-native::release - Native Image at ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/release-native"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_images:
    name: 'Build Native Image ${{ matrix.platform }}'
    needs: clean_release
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
          - os: 'ubuntu-24.04-arm'
            platform: 'linux-arm64'
          - os: 'macos-latest'
            platform: 'darwin-arm64'
          - os: 'macos-14'
            platform: 'darwin-amd64'
          - os: 'windows-latest'
            platform: 'win-amd64'
          #- os: 'windows-11-arm' # TO DO: check later, see https://github.com/metanorma/mnconvert/issues/431#issuecomment-3113974980
          #  platform: 'win-arm64'
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: graalvm
          cache: maven

      - name: Set the release version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        shell: bash

      - name: Set the DateTime
        shell: bash
        run: echo "DATETIME=$(date -u +'%F at %T (UTC)')" >> $GITHUB_ENV

      - name: Build mnconvert native image
        shell: bash
        run: mvn -Pnative --settings settings.xml -DskipTests clean package # shade:shade

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: "mnconvert-${{ matrix.platform }}-v${{ env.VERSION }}.zip"
          directory: target/native/nativeCompile/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "target/native/nativeCompile/mnconvert-${{ matrix.platform }}-v${{ env.VERSION }}.zip"
          file_glob: true
          tag: release-native
          release_name: Release v${{ env.VERSION }} (Native Image)
          overwrite: true
          make_latest: false
          prerelease: false
          body: |
              This is a [Native Image](https://www.graalvm.org/latest/reference-manual/native-image/) release of mnconvert tool.
